### ISSUE TITLE
prov/gni: Deadlock in __gnix_wait_nic_prog_thread_fn on gnix_nic_list_lock

### ISSUE THREAD

**Issue by jshimek** [ofi-cray/libfabric-cray#1337]
If the mr reg code gets called from _gnix_wait_nic_prog_thread_fn the application will deadlock.
the mr code takes the gnix_nic_list_lock and can be called from _nic_progress.. The __gnix_wait_nic_prog_thread_fn takes the nic_list_lock to prevent nics from being destroyed while we are progressing them.

Thread 2 (Thread 0x2aaaba402700 (LWP 10157)):
#0  0x00002aaaabf0779c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00002aaaabf03489 in _L_lock_918 () from /lib64/libpthread.so.0
#2  0x00002aaaabf032b0 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00002aaaaafab86b in __gnix_generic_register (domain=0x609940, md=0x2aaacc000910, address=0x2aaaba806000, length=16384, dst_cq_hndl=0x0, flags=0, vmdh_index=-1) at prov/gni/src/gnix_mr.c:362
#4  0x00002aaaaafac7ea in __gnix_register_region (handle=0x2aaacc000910, address=0x2aaaba806000, length=16384, fi_reg_context=0x2aaaba4016e0, context=0x609940) at prov/gni/src/gnix_mr.c:436
#5  0x00002aaaaafb7c9f in __mr_cache_create_registration (cache=0x64fa30, address=46912761782272, length=16384, entry=0x2aaaba4015c8, key=0x2aaaba4015d0, fi_reg_context=0x2aaaba4016e0)
    at prov/gni/src/gnix_mr_cache.c:1447
#6  0x00002aaaaafb8962 in _gnix_mr_cache_register (cache=0x64fa30, address=46912761782272, length=16384, fi_reg_context=0x2aaaba4016e0, handle=0x2aaaba401708) at prov/gni/src/gnix_mr_cache.c:1565
#7  0x00002aaaaafadc9e in __cache_reg_mr (domain=0x609940, address=46912761782272, length=16384, fi_reg_context=0x2aaaba4016e0, handle=0x2aaaba401708) at prov/gni/src/gnix_mr.c:714
#8  0x00002aaaaafaad7a in __mr_reg (fid=0x609940, buf=0x2aaaba806000, len=16384, access=768, offset=0, requested_key=0, flags=0, mr_o=0x2aaaba4019f8, context=0x0) at prov/gni/src/gnix_mr.c:216
#9  0x00002aaaaafab1db in gnix_mr_regattr (fid=0x609940, attr=0x2aaaba401820, flags=0, mr=0x2aaaba4019f8) at prov/gni/src/gnix_mr.c:298
#10 0x00002aaaaafab089 in gnix_mr_reg (fid=0x609940, buf=0x2aaaba806000, len=16384, access=768, offset=0, requested_key=0, flags=0, mr=0x2aaaba4019f8, context=0x0) at prov/gni/src/gnix_mr.c:262
#11 0x00002aaaaafc1c12 in __gnix_rndzv_req (arg=0x6a1b00) at prov/gni/src/gnix_msg.c:1032
#12 0x00002aaaab009d53 in __gnix_vc_push_work_reqs (vc=0x632618) at prov/gni/src/gnix_vc.c:1813
#13 0x00002aaaab00bb53 in _gnix_vc_nic_progress (nic=0x62ad90) at prov/gni/src/gnix_vc.c:2052
#14 0x00002aaaaafd88d0 in _gnix_nic_progress (arg=0x62ad90) at prov/gni/src/gnix_nic.c:576
#15 0x00002aaaab014c11 in __gnix_wait_nic_prog_thread_fn (the_arg=0x0) at prov/gni/src/gnix_wait.c:138
#16 0x00002aaaabf010a4 in start_thread () from /lib64/libpthread.so.0
#17 0x00002aaaac3ff02d in clone () from /lib64/libc.so.6
@ztiffany @hppritcha @sungeunchoi @jswaro

**Comment by jshimek** [comment]
Closing since my commit message added a reference but did not auto close the issue...
