### ISSUE TITLE
Segfault in fi_close w/counters

### ISSUE THREAD

**Issue by agontarek** [ofi-cray/libfabric-cray#981]
Found two bugs in the gni provider that results in a segfault.

If I close a counter before closing the endpoint (which is incorrect behavior according to the manpages), I get a segfault during the close of the endpoint:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004efe48 in slist_empty (list=0x88) at craylibs/ofi/include/fi_list.h:143
143         craylibs/ofi/include/fi_list.h: No such file or directory.
(gdb) bt
#0  0x00000000004efe48 in slist_empty (list=0x88) at craylibs/ofi/include/fi_list.h:143
#1  0x00000000004f06ff in gnix_wait_close (wait=0x0) at craylibs/ofi/prov/gni/src/gnix_wait.c:273
#2  0x000000000050f523 in __cntr_destruct (obj=0xe70000) at craylibs/ofi/prov/gni/src/gnix_cntr.c:279
#3  0x0000000000530dc1 in __ep_destruct (obj=0xb30340) at craylibs/ofi/prov/gni/src/gnix_ep.c:1194
#4  0x0000000000530fe1 in gnix_ep_close (fid=0xb30340) at craylibs/ofi/prov/gni/src/gnix_ep.c:1245
#5  0x00000000004cbeb5 in libpgas::OFI_Gni<true>::~OFI_Gni() ()
#6  0x00000000004cc3c1 in libpgas::OFI_Gni<true>::~OFI_Gni() ()
#7  0x000000000049adc7 in libpgas::OFI_State::finalize() ()
#8  0x000000000049958f in libpgas::OFI_Gni_System::~OFI_Gni_System() ()
#9  0x0000000000499641 in libpgas::OFI_Gni_System::~OFI_Gni_System() ()
#10 0x00000000004487e2 in libpgas::System::finalize(int) ()
#11 0x000000000064a869 in __run_exit_handlers (status=0, listp=0x9cb998 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:68
#12 0x000000000064a8d3 in exit (status=<optimized out>) at exit.c:104
#13 0x0000000000641a07 in __libc_start_main (main=0x40b660 <main>, argc=1, argv=0x7fffffff5928, init=0x641e90 <__libc_csu_init>, fini=0x641f20 <__libc_csu_fini>, rtld_fini=0x0, stack_end=0x7fffffff5918) at libc-start.c:319
#14 0x000000000040b417 in _start () at ../sysdeps/x86_64/start.S:122
```

Note that `fi_close()` on a counter that is still bound to an endpoint is supposed to return 
`-FI_EBUSY` according to the manpages, which is not happening with the gni provider.

If I change the behavior to close the endpoint first, I get a segfault in `fi_close()` on the counter:

```
#0  0x00000000004ef9c8 in slist_empty (list=0x88) at craylibs/ofi/include/fi_list.h:143
143         craylibs/ofi/include/fi_list.h: No such file or directory.
(gdb) bt
#0  0x00000000004ef9c8 in slist_empty (list=0x88) at craylibs/ofi/include/fi_list.h:143
#1  0x00000000004f027f in gnix_wait_close (wait=0x0) at craylibs/ofi/prov/gni/src/gnix_wait.c:273
#2  0x000000000050f0a3 in __cntr_destruct (obj=0xe70000) at craylibs/ofi/prov/gni/src/gnix_cntr.c:279
#3  0x000000000050f196 in gnix_cntr_close (fid=0xe70000) at craylibs/ofi/prov/gni/src/gnix_cntr.c:300
#4  0x00000000004cbb6c in libpgas::OFI_Gni<true>::~OFI_Gni() ()
#5  0x00000000004cbf61 in libpgas::OFI_Gni<true>::~OFI_Gni() ()
#6  0x000000000049adc7 in libpgas::OFI_State::finalize() ()
#7  0x000000000049958f in libpgas::OFI_Gni_System::~OFI_Gni_System() ()
#8  0x0000000000499641 in libpgas::OFI_Gni_System::~OFI_Gni_System() ()
#9  0x00000000004487e2 in libpgas::System::finalize(int) ()
#10 0x000000000064a3e9 in __run_exit_handlers (status=0, listp=0x9caa58 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:68
#11 0x000000000064a453 in exit (status=<optimized out>) at exit.c:104
#12 0x0000000000641587 in __libc_start_main (main=0x40b660 <main>, argc=1, argv=0x7fffffff5928, init=0x641a10 <__libc_csu_init>, fini=0x641aa0 <__libc_csu_fini>, rtld_fini=0x0, stack_end=0x7fffffff5918) at libc-start.c:319
#13 0x000000000040b417 in _start () at ../sysdeps/x86_64/start.S:122
```

Note that I am using `FI_WAIT_UNSPEC` for the wait set on the counter:

```
    cntr_attr.events = FI_CNTR_EVENTS_COMP;     // Count completion events
    cntr_attr.wait_obj = FI_WAIT_UNSPEC;        // Let provider determine wait object
    cntr_attr.wait_set = NULL;                  // Optional wait set obj
    cntr_attr.flags = 0;                        // Required to be 0 for now
    m_nbi_cntr = OFI::cntr_open(m_domain, cntr_attr);
```

**Comment by hppritcha** [comment]
could you provide a simple test if possible?

**Comment by hppritcha** [comment]
taking this one.  there's no refcn'ting on wait objects right now.
